language: python

install:
    - pip install -e .

matrix:
    include:
        - os: linux
          python: 3.2
        - os: linux
          python: 3.3
        - os: osx
          language: generic
        - os: osx
          language: generic
script:
    - pytest
