version: "3.6"

services:

    tobiiglasses2:
      image: "python:3.8-buster"

      container_name: tobiiglasses2

      network_mode: "host"
      environment:
        - "DISPLAY=${DISPLAY}"
        - "QT_X11_NO_MITSHM=1"
        - "PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native"

      privileged: true
      stdin_open: true
      tty: true

      volumes:
        - type: bind
          source: ../
          target: /home/TobiiGlassesPyController

        - type: bind
          source: ./init.sh
          target: /home/init.sh

        - type: bind
          source: ${XDG_RUNTIME_DIR}/pulse
          target: ${XDG_RUNTIME_DIR}/pulse

      entrypoint: ["bash", "/home/init.sh"]
